server:
  port: 8080

spring:
  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials
      routes:
        # Route pour les requêtes REST classiques
        - id: messaging-rest
          uri: http://messaging-service:8083
          predicates:
            - Path=/api/messages/**
        
        # 2. Route pour le WebSocket (SockJS)
        - id: messaging-ws
          uri: http://messaging-service:8083
          predicates:
            - Path=/ws/**