server:
  port: 8083

spring:
  data:
    mongodb:
    uri: ${SPRING_DATA_MONGODB_URI:mongodb://mongodb:27017/messaging_db}
  rabbitmq:
    host: rabbitmq

# Cette partie normallement devrait prendre des variables d'environnement mais nous allons l'implémenter ainsi pour vous 
# permettre de démarrer rapidement
encryption: 
  salt: ef5b4c42a42e5b2c
  password: voom-pass
  